name: hoge

on:
  workflow_dispatch:

jobs:
  hogejob:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build
        run: |
          echo "Build"
          which aws
