name: hoge

on:
  push:
    branches:
      - hoge
  workflow_dispatch:

jobs:
  hogejob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build
        run: |
          echo "Build"
      - name: Test
        run: |
          echo "Test"
